# Generated by Django 4.1.3 on 2022-11-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('located', models.CharField(choices=[('Dry', 'Dry'), ('Frozen', 'Frozen'), ('Walkin', 'Walkin'), ('Lowboy', 'Lowboy')], max_length=6)),
                ('to_whiteboard', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('par', models.CharField(max_length=200)),
                ('on_hand', models.CharField(max_length=200)),
                ('exp_date', models.CharField(max_length=200)),
                ('flag', models.CharField(choices=[('Dry', 'Dry'), ('Frozen', 'Frozen'), ('Walkin', 'Walkin'), ('Lowboy', 'Lowboy')], max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('shift', models.CharField(choices=[('Opening', 'Opening'), ('Closing', 'Closing')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('New', 'New'), ('Out', 'Out'), ('Gone', 'Gone'), ('Change', 'Change')], max_length=6)),
            ],
        ),
    ]
