# Generated by Django 4.1.3 on 2022-11-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(null=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('New', 'New'), ('Out', 'Out'), ('Gone', 'Gone'), ('Change', 'Change')], max_length=6)),
            ],
        ),
    ]
