# Generated by Django 4.1.3 on 2022-12-07 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipetasks',
            name='prep',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.prep'),
        ),
        migrations.AddField(
            model_name='recipetasks',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_tasks',
            field=models.ManyToManyField(blank=True, through='base.RecipeTasks', to='base.prep'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prep',
            name='task_for',
            field=models.ManyToManyField(blank=True, through='base.RecipeTasks', to='base.recipe'),
        ),
        migrations.AddField(
            model_name='prep',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to=settings.AUTH_USER_MODEL),
        ),
    ]
